### PR TITLE
Add module map

### LINKED ISSUE #25: How to Import in Swift?
I recently migrated my project from Objective C to Swift and was unable to import this SDK.

I tried `import SurveyMonkeyiOSSDK` but it is unable to find SurveyMonkey in my list of modules.

Weirdly, my CocoaPods module only shows the Header files. When I import the framework manually into my project, it still doesn't show up.

image

Any help here?

Regards,
Puneet

### PR DESCRIPTION
**Pull request by plu**
Fix #25

### CODE REVIEW

**Comment by thomasjoulin** [comment]
can this be merged

**Comment by TimurAsayonok** [comment]
@thomasjoulin @plu do you have any news about when it can be merged and released?

**Comment by TimurAsayonok** [comment]
Oh my god 😂

**Comment by hiteshjain29** [comment]
Closing as its got fixed xc-framework.

**Pull request closed without merging**
